### ISSUE TITLE
Caching for Flutter Install

### ISSUE THREAD

**Issue by ChristianNavolskyi** [hey24sheep/azure-flutter-tasks#2]
Is it possible to cache the flutter installation in Azure Pipelines?

I tried to cache the folder under `$(Agent.ToolsDirectory)/Flutter/2.2.3-stable/macos` but after the cache was restored, `FlutterInstall` started downloading and unzipping an archive again.

**Comment by hey24sheep** [comment]
@ChristianNavolskyi Yes, you can cache it for in between builds. `FlutterInstall` started because you might have not put a control condition on it. To put a condition on it, go to `Control Options -> Run this task (Select-> Custom Conditions) -> Custom Condition (Input box will appear)` put your `ne(variables.cacheHitVar, 'true')` replace `cacheHitVar` with your cache hit variable. Refer to [Azure Pipeline Caching](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops) and [Tut-Azure Cache Task](https://dev.to/n3wt0n/how-to-reduce-build-time-using-caching-in-azure-pipelines-59f6)

**Comment by ChristianNavolskyi** [comment]
Hey @hey24sheep thanks for the quick reply.

Looking at the code in [index.ts](https://github.com/hey24sheep/azure-flutter-tasks/blob/master/tasks/install/index.ts#L36) I assumed, that `FlutterInstall` checks the directory for an existing installation.

Don't I still need `FlutterInstall` to set the environment variables? We use `$(FlutterToolPath)/flutter` to use `flutter` commands.

**Comment by hey24sheep** [comment]
You are right, it checks the directory for installation, I didn't write the caching part of the Build Task, original author did. If you look at the debug verbose below you will see the cache dir is set but when it is looked up in next run, it shows it as empty. I don't know how it can be fixed or what is wrong here as the documentation isn't there for extensions especially regarding caching. 

``` dart
[debug]check path : D:\a\_tasks\FlutterInstall_83c91e05-bdf9-42ce-b27e-6dae8771294e\0.2.41\node_modules\azure-pipelines-tool-lib\lib.json
[debug]adding resource file: D:\a\_tasks\FlutterInstall_83c91e05-bdf9-42ce-b27e-6dae8771294e\0.2.41\node_modules\azure-pipelines-tool-lib\lib.json
[debug]system.culture=en-US
[debug]channel=stable
[debug]version=custom
[debug]Finding version 'custom' from 'https://storage.googleapis.com/flutter_infra/releases/releases_windows.json'
[debug]customVersion=1.22.6
[debug]Found version hash '9b2d32b605630f28625709ebd9d78ab3016b2bf6'
[debug]Trying to get (Flutter,1.22.6-stable, windows) tool from local cache
[debug]isExplicit: 1.22.6-stable
[debug]explicit? true
[debug]Agent.Version=2.184.2
[debug]Agent.ToolsDirectory=C:\hostedtoolcache\windows
[debug]checking cache: C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows
[debug]not found
[debug]Starting download archive from 'https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_1.22.6-stable.zip'
[debug]
[debug]Agent.Version=2.184.2
[debug]Agent.TempDirectory=D:\a\_temp
[debug]testing directory 'D:\a\_temp'
[debug]destination D:\a\_temp\b58794df-0e13-4d9c-8f05-72ff2ea01e72
[debug]downloading
[debug]creating stream
[debug]download complete
[debug]Succeeded to download 'D:\a\_temp\b58794df-0e13-4d9c-8f05-72ff2ea01e72' archive from 'https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_1.22.6-stable.zip'
[debug]Extracting 'https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_1.22.6-stable.zip' archive
[debug]Agent.Version=2.184.2
[debug]Agent.TempDirectory=D:\a\_temp
[debug]testing directory 'D:\a\_temp\7a225982-7602-4e6d-8cea-3a26b3c034fa'
[debug]testing directory 'D:\a\_temp'
[debug]mkdir 'D:\a\_temp\7a225982-7602-4e6d-8cea-3a26b3c034fa'
[debug]which 'C:\Windows\system32\chcp.com'
[debug]found: 'C:\Windows\system32\chcp.com'
[debug]C:\Windows\system32\chcp.com arg: 65001
[debug]C:\Windows\system32\chcp.com arg: 65001
[debug]exec tool: C:\Windows\system32\chcp.com
[debug]exec tool: C:\Windows\system32\chcp.com
[debug]arguments:
[debug]arguments:
[debug]   65001
[debug]   65001
[debug]Exit code 0 received from tool 'C:\Windows\system32\chcp.com'
[debug]Exit code 0 received from tool 'C:\Windows\system32\chcp.com'
[debug]STDIO streams have closed for tool 'C:\Windows\system32\chcp.com'
[debug]STDIO streams have closed for tool 'C:\Windows\system32\chcp.com'
[debug]which 'powershell'
[debug]found: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
[debug]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe arg: -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command
[debug]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe arg: $ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\b58794df-0e13-4d9c-8f05-72ff2ea01e72', 'D:\a\_temp\7a225982-7602-4e6d-8cea-3a26b3c034fa')
[debug]exec tool: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
[debug]arguments:
[debug]   -NoLogo
[debug]   -Sta
[debug]   -NoProfile
[debug]   -NonInteractive
[debug]   -ExecutionPolicy
[debug]   Unrestricted
[debug]   -Command
[debug]   $ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\b58794df-0e13-4d9c-8f05-72ff2ea01e72', 'D:\a\_temp\7a225982-7602-4e6d-8cea-3a26b3c034fa')
[debug]Exit code 0 received from tool 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
[debug]STDIO streams have closed for tool 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
[debug]Extracted to 'D:\a\_temp\7a225982-7602-4e6d-8cea-3a26b3c034fa' 'https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_1.22.6-stable.zip' archive
[debug]Adding 'D:\a\_temp\7a225982-7602-4e6d-8cea-3a26b3c034fa' to cache (Flutter,1.22.6-stable, windows)
[debug]source dir: D:\a\_temp\7a225982-7602-4e6d-8cea-3a26b3c034fa
[debug]Agent.Version=2.184.2
[debug]Agent.ToolsDirectory=C:\hostedtoolcache\windows
[debug]destination C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows
[debug]rm -rf C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows
[debug]rm -rf C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows.complete
[debug]testing directory 'C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows'
[debug]testing directory 'C:\hostedtoolcache\windows\Flutter\1.22.6-stable'
[debug]testing directory 'C:\hostedtoolcache\windows\Flutter'
[debug]testing directory 'C:\hostedtoolcache\windows'
[debug]mkdir 'C:\hostedtoolcache\windows\Flutter'
[debug]mkdir 'C:\hostedtoolcache\windows\Flutter\1.22.6-stable'
[debug]mkdir 'C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows'
[debug]Agent.Version=2.184.2
[debug]Agent.ToolsDirectory=C:\hostedtoolcache\windows
[debug]finished caching tool
[debug]Trying again to get (Flutter,1.22.6-stable, windows) tool from local cache
[debug]isExplicit: 1.22.6-stable
[debug]explicit? true
[debug]Agent.Version=2.184.2
[debug]Agent.ToolsDirectory=C:\hostedtoolcache\windows
[debug]checking cache: C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows
[debug]Set FlutterToolPath with 'C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows\flutter\bin'
[debug]set FlutterToolPath=C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows\flutter\bin
[debug]Processed: ##vso[task.setvariable variable=FlutterToolPath;issecret=false;]C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows\flutter\bin
[debug]Set DartToolPath with 'C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows\flutter\.pub-cache\bin'
[debug]set FlutterPubCachePath=C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows\flutter\.pub-cache\bin
[debug]Processed: ##vso[task.setvariable variable=FlutterPubCachePath;issecret=false;]C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows\flutter\.pub-cache\bin
[debug]Set DartToolPath with 'C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows\flutter\bin\cache\dart-sdk\bin'
[debug]set DartToolPath=C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows\flutter\bin\cache\dart-sdk\bin
[debug]Processed: ##vso[task.setvariable variable=DartToolPath;issecret=false;]C:\hostedtoolcache\windows\Flutter\1.22.6-stable\windows\flutter\bin\cache\dart-sdk\bin
[debug]task result: Succeeded
[debug]Processed: ##vso[task.complete result=Succeeded;]Installed

```

**Comment by ChristianNavolskyi** [comment]
I just ran it locally and the caching seems to work as expected.

Here is the output of the first run:
```
##vso[task.debug]agent.TempDirectory=/Users/cnavolskyi/documents/azure/temp
##vso[task.debug]loading inputs and endpoints
##vso[task.debug]loading INPUT_MODE
##vso[task.debug]loading INPUT_CHANNEL
##vso[task.debug]loading INPUT_VERSION
##vso[task.debug]loaded 3
##vso[task.debug]Agent.ProxyUrl=undefined
##vso[task.debug]Agent.CAInfo=undefined
##vso[task.debug]Agent.ClientCert=undefined
##vso[task.debug]Agent.SkipCertValidation=undefined
##vso[task.debug]Agent.ProxyUrl=undefined
##vso[task.debug]Agent.CAInfo=undefined
##vso[task.debug]Agent.ClientCert=undefined
##vso[task.debug]check path : /Users/cnavolskyi/Documents/azure/azure-flutter-tasks/tasks/install/node_modules/azure-pipelines-tool-lib/lib.json
##vso[task.debug]adding resource file: /Users/cnavolskyi/Documents/azure/azure-flutter-tasks/tasks/install/node_modules/azure-pipelines-tool-lib/lib.json
##vso[task.debug]system.culture=undefined
##vso[task.debug]mode=auto
##vso[task.debug]channel=stable
##vso[task.debug]version=latest
##vso[task.debug]Finding version 'latest' from 'https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json'
##vso[task.debug]Found version hash 'f4abaa0735eba4dfd8f33f73363911d63931fe03'
##vso[task.debug]Trying to get (Flutter,2.2.3-stable, macos) tool from local cache
##vso[task.debug]isExplicit: 2.2.3-stable
##vso[task.debug]explicit? true
##vso[task.debug]Agent.Version=undefined
##vso[task.debug]Agent.ToolsDirectory=/Users/cnavolskyi/documents/azure
##vso[task.debug]checking cache: /Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos
##vso[task.debug]not found
##vso[task.debug]Starting download archive from 'https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.2.3-stable.zip'
##vso[task.debug]
##vso[task.debug]Agent.Version=undefined
##vso[task.debug]Agent.TempDirectory=/Users/cnavolskyi/documents/azure/temp
##vso[task.debug]testing directory '/Users/cnavolskyi/documents/azure/temp'
Downloading: https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.2.3-stable.zip
##vso[task.debug]destination /Users/cnavolskyi/documents/azure/temp/d01575c8-63f5-49b3-93d7-332dd27b76d3
##vso[task.debug]downloading
##vso[task.debug]creating stream
##vso[task.debug]download complete
##vso[task.debug]Succeeded to download '/Users/cnavolskyi/documents/azure/temp/d01575c8-63f5-49b3-93d7-332dd27b76d3' archive from 'https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.2.3-stable.zip'
##vso[task.debug]Extracting 'https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.2.3-stable.zip' archive
Extracting archive
##vso[task.debug]Agent.Version=undefined
##vso[task.debug]Agent.TempDirectory=/Users/cnavolskyi/documents/azure/temp
##vso[task.debug]testing directory '/Users/cnavolskyi/documents/azure/temp/6706fcb4-956e-4ab0-8f18-56f63bd226bf'
##vso[task.debug]testing directory '/Users/cnavolskyi/documents/azure/temp'
##vso[task.debug]mkdir '/Users/cnavolskyi/documents/azure/temp/6706fcb4-956e-4ab0-8f18-56f63bd226bf'
##vso[task.debug]which 'unzip'
##vso[task.debug]found: '/usr/bin/unzip'
##vso[task.debug]/usr/bin/unzip arg: /Users/cnavolskyi/documents/azure/temp/d01575c8-63f5-49b3-93d7-332dd27b76d3
##vso[task.debug]exec tool: /usr/bin/unzip
##vso[task.debug]arguments:
##vso[task.debug]   /Users/cnavolskyi/documents/azure/temp/d01575c8-63f5-49b3-93d7-332dd27b76d3
[command]/usr/bin/unzip /Users/cnavolskyi/documents/azure/temp/d01575c8-63f5-49b3-93d7-332dd27b76d3
Archive:  /Users/cnavolskyi/documents/azure/temp/d01575c8-63f5-49b3-93d7-332dd27b76d3
   creating: flutter/
  inflating: flutter/CODE_OF_CONDUCT.md  
  inflating: flutter/.ci.yaml        
  inflating: flutter/LICENSE         
   creating: flutter/bin/
...
  inflating: flutter/.idea/vcs.xml   
  inflating: flutter/.idea/modules.xml  
 extracting: flutter/.idea/.name     
finishing deferred symbolic links:
  flutter/bin/cache/artifacts/engine/darwin-x64-profile/FlutterMacOS.framework/Resources -> Versions/Current/Resources
  flutter/bin/cache/artifacts/engine/darwin-x64-profile/FlutterMacOS.framework/Versions/Current -> A
  flutter/bin/cache/artifacts/engine/darwin-x64-profile/FlutterMacOS.framework/Headers -> Versions/Current/Headers
  flutter/bin/cache/artifacts/engine/darwin-x64-profile/FlutterMacOS.framework/Modules -> Versions/Current/Modules
  flutter/bin/cache/artifacts/engine/darwin-x64-profile/FlutterMacOS.framework/FlutterMacOS -> Versions/Current/FlutterMacOS
  flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Resources -> Versions/Current/Resources
  flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Versions/Current -> A
  flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Headers -> Versions/Current/Headers
  flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Modules -> Versions/Current/Modules
  flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/FlutterMacOS -> Versions/Current/FlutterMacOS
  flutter/bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.framework/Resources -> Versions/Current/Resources
  flutter/bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.framework/Versions/Current -> A
  flutter/bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.framework/Headers -> Versions/Current/Headers
  flutter/bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.framework/Modules -> Versions/Current/Modules
  flutter/bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.framework/FlutterMacOS -> Versions/Current/FlutterMacOS
  flutter/.pub-cache/hosted/pub.dartlang.org/test-1.16.8/doc/package_config.md -> configuration.md
##vso[task.debug]Exit code 0 received from tool '/usr/bin/unzip'
##vso[task.debug]STDIO streams have closed for tool '/usr/bin/unzip'
##vso[task.debug]Extracted to '/Users/cnavolskyi/documents/azure/temp/6706fcb4-956e-4ab0-8f18-56f63bd226bf' 'https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.2.3-stable.zip' archive
##vso[task.debug]Adding '/Users/cnavolskyi/documents/azure/temp/6706fcb4-956e-4ab0-8f18-56f63bd226bf' to cache (Flutter,2.2.3-stable, macos)
Caching tool: Flutter 2.2.3-stable macos
##vso[task.debug]source dir: /Users/cnavolskyi/documents/azure/temp/6706fcb4-956e-4ab0-8f18-56f63bd226bf
##vso[task.debug]Agent.Version=undefined
##vso[task.debug]Agent.ToolsDirectory=/Users/cnavolskyi/documents/azure
##vso[task.debug]destination /Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos
##vso[task.debug]rm -rf /Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos
##vso[task.debug]rm -rf /Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos.complete
##vso[task.debug]testing directory '/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos'
##vso[task.debug]testing directory '/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable'
##vso[task.debug]testing directory '/Users/cnavolskyi/documents/azure/Flutter'
##vso[task.debug]testing directory '/Users/cnavolskyi/documents/azure'
##vso[task.debug]mkdir '/Users/cnavolskyi/documents/azure/Flutter'
##vso[task.debug]mkdir '/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable'
##vso[task.debug]mkdir '/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos'
##vso[task.debug]Agent.Version=undefined
##vso[task.debug]Agent.ToolsDirectory=/Users/cnavolskyi/documents/azure
##vso[task.debug]finished caching tool
##vso[task.debug]Trying again to get (Flutter,2.2.3-stable, macos) tool from local cache
##vso[task.debug]isExplicit: 2.2.3-stable
##vso[task.debug]explicit? true
##vso[task.debug]Agent.Version=undefined
##vso[task.debug]Agent.ToolsDirectory=/Users/cnavolskyi/documents/azure
##vso[task.debug]checking cache: /Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos
Found tool in cache: Flutter 2.2.3-stable macos
##vso[task.debug]Set FlutterToolPath with '/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/bin'
##vso[task.debug]set FlutterToolPath=/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/bin
##vso[task.setvariable variable=FlutterToolPath;issecret=false;]/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/bin
##vso[task.debug]Set DartToolPath with '/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/.pub-cache/bin'
##vso[task.debug]set FlutterPubCachePath=/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/.pub-cache/bin
##vso[task.setvariable variable=FlutterPubCachePath;issecret=false;]/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/.pub-cache/bin
##vso[task.debug]Set DartToolPath with '/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/bin/cache/dart-sdk/bin'
##vso[task.debug]set DartToolPath=/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/bin/cache/dart-sdk/bin
##vso[task.setvariable variable=DartToolPath;issecret=false;]/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/bin/cache/dart-sdk/bin
##vso[task.debug]task result: Succeeded
##vso[task.complete result=Succeeded;]Installed
```

And the second run:
```
##vso[task.debug]agent.TempDirectory=/Users/cnavolskyi/documents/azure/temp
##vso[task.debug]loading inputs and endpoints
##vso[task.debug]loading INPUT_MODE
##vso[task.debug]loading INPUT_CHANNEL
##vso[task.debug]loading INPUT_VERSION
##vso[task.debug]loaded 3
##vso[task.debug]Agent.ProxyUrl=undefined
##vso[task.debug]Agent.CAInfo=undefined
##vso[task.debug]Agent.ClientCert=undefined
##vso[task.debug]Agent.SkipCertValidation=undefined
##vso[task.debug]Agent.ProxyUrl=undefined
##vso[task.debug]Agent.CAInfo=undefined
##vso[task.debug]Agent.ClientCert=undefined
##vso[task.debug]check path : /Users/cnavolskyi/Documents/azure/azure-flutter-tasks/tasks/install/node_modules/azure-pipelines-tool-lib/lib.json
##vso[task.debug]adding resource file: /Users/cnavolskyi/Documents/azure/azure-flutter-tasks/tasks/install/node_modules/azure-pipelines-tool-lib/lib.json
##vso[task.debug]system.culture=undefined
##vso[task.debug]mode=auto
##vso[task.debug]channel=stable
##vso[task.debug]version=latest
##vso[task.debug]Finding version 'latest' from 'https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json'
##vso[task.debug]Found version hash 'f4abaa0735eba4dfd8f33f73363911d63931fe03'
##vso[task.debug]Trying to get (Flutter,2.2.3-stable, macos) tool from local cache
##vso[task.debug]isExplicit: 2.2.3-stable
##vso[task.debug]explicit? true
##vso[task.debug]Agent.Version=undefined
##vso[task.debug]Agent.ToolsDirectory=/Users/cnavolskyi/documents/azure
##vso[task.debug]checking cache: /Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos
Found tool in cache: Flutter 2.2.3-stable macos
##vso[task.debug]Set FlutterToolPath with '/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/bin'
##vso[task.debug]set FlutterToolPath=/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/bin
##vso[task.setvariable variable=FlutterToolPath;issecret=false;]/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/bin
##vso[task.debug]Set DartToolPath with '/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/.pub-cache/bin'
##vso[task.debug]set FlutterPubCachePath=/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/.pub-cache/bin
##vso[task.setvariable variable=FlutterPubCachePath;issecret=false;]/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/.pub-cache/bin
##vso[task.debug]Set DartToolPath with '/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/bin/cache/dart-sdk/bin'
##vso[task.debug]set DartToolPath=/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/bin/cache/dart-sdk/bin
##vso[task.setvariable variable=DartToolPath;issecret=false;]/Users/cnavolskyi/documents/azure/Flutter/2.2.3-stable/macos/flutter/bin/cache/dart-sdk/bin
##vso[task.debug]task result: Succeeded
##vso[task.complete result=Succeeded;]Installed
```

Any idea why it didn't work on the pipeline?

**Comment by hey24sheep** [comment]
Oh, I have no clue why it doesn't work on pipelines then. It should as per Microsoft's documentation. I will keep this open, maybe someone with more knowledge about DevOps can help.

**Comment by ChristianNavolskyi** [comment]
Thanks for investigating.
Hope this will be fixed soon. On top the macos VMs seem to run very slowly
compared to an Ubuntu image, so caching would be very much appreciated

**Comment by hey24sheep** [comment]
@ChristianNavolskyi It seems caching is working now. It was an issue from Azure's side. Could you please check your builds too, so I can close this issue if it's fixed.

Log of first build
```
2021-08-16T14:08:01.3851392Z ##[section]Starting: Flutter Install
2021-08-16T14:08:01.3992942Z ==============================================================================
2021-08-16T14:08:01.3993288Z Task         : Flutter Install Task
2021-08-16T14:08:01.3993549Z Description  : Install the Flutter environment.
2021-08-16T14:08:01.3993772Z Version      : 0.2.43
2021-08-16T14:08:01.3993991Z Author       : Hey24sheep
2021-08-16T14:08:01.3994365Z Help         : For more information, take a look at the Flutter [documentation](https://flutter.io)
2021-08-16T14:08:01.3994794Z ==============================================================================
2021-08-16T14:08:02.6431684Z Downloading: https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_1.22.6-stable.zip
2021-08-16T14:08:04.5602611Z Extracting archive
2021-08-16T14:08:04.5675571Z [command]C:\Windows\system32\chcp.com 65001
2021-08-16T14:08:04.5812012Z Active code page: 65001
2021-08-16T14:08:04.5822097Z 
2021-08-16T14:08:04.5996612Z [command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\10b59996-89e6-4e4b-9100-39dd3b0d1d2c', 'D:\a\_temp\bf4bff63-d7a2-472f-978a-aa410e6c8a24')"
2021-08-16T14:08:11.2443541Z 
2021-08-16T14:08:11.2588962Z Caching tool: Flutter 1.22.6-stable windows
2021-08-16T14:08:20.8196011Z Found tool in cache: Flutter 1.22.6-stable windows
2021-08-16T14:08:20.8517919Z ##[section]Finishing: Flutter Install
```

Log of second build
``` 
2021-08-16T14:48:59.7807272Z ##[section]Starting: Flutter Install
2021-08-16T14:48:59.7914995Z ==============================================================================
2021-08-16T14:48:59.7915339Z Task         : Flutter Install Task
2021-08-16T14:48:59.7915632Z Description  : Install the Flutter environment.
2021-08-16T14:48:59.7915873Z Version      : 0.2.43
2021-08-16T14:48:59.7916105Z Author       : Hey24sheep
2021-08-16T14:48:59.7916483Z Help         : For more information, take a look at the Flutter [documentation](https://flutter.io)
2021-08-16T14:48:59.7916928Z ==============================================================================
2021-08-16T14:49:00.7780681Z Downloading: https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_1.22.6-stable.zip
2021-08-16T14:49:01.9161364Z Extracting archive
2021-08-16T14:49:01.9213314Z [command]C:\Windows\system32\chcp.com 65001
2021-08-16T14:49:01.9304194Z Active code page: 65001
2021-08-16T14:49:01.9308041Z 
2021-08-16T14:49:01.9503069Z [command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\5de917b8-5da2-4896-9572-aac888ae740d', 'D:\a\_temp\a7359725-e90b-4ba6-babb-3cd82831782c')"
2021-08-16T14:49:07.9496101Z 
2021-08-16T14:49:07.9719927Z Caching tool: Flutter 1.22.6-stable windows
2021-08-16T14:49:21.3371333Z Found tool in cache: Flutter 1.22.6-stable windows
2021-08-16T14:49:21.3686859Z ##[section]Finishing: Flutter Install
```

**Comment by ChristianNavolskyi** [comment]
Isn't it showing twice the same? Both start with Downloading from googleapis, then extracting the archive...

**Comment by hey24sheep** [comment]
@ChristianNavolskyi I am so sorry, that's embarrasing :( I didn't check it properly. Were you able to use cache task with flutter tasks?

Looking at Azure pipeline issues [issue](https://github.com/microsoft/azure-pipelines-tasks/issues/14980) it's an issue with pipelines.

**Comment by ChristianNavolskyi** [comment]
The Cache task is restoring the cache, but flutter install still downloads it freshly from google and extracts it.

Looks like we still have to wait for a fix.

**Comment by hey24sheep** [comment]
I see, well hope they fix it soon.

**Comment by andiahmadfauzy** [comment]
any update on this?

**Comment by hey24sheep** [comment]
I have just pushed a major update, you could try on the latest and see if it is caching or not. 

You can track the changes [here](https://github.com/hey24sheep/azure-flutter-tasks/blob/master/CHANGELOG.md).

**Comment by ChristianNavolskyi** [comment]
I just triggered our pipeline, but it's still not working 😞 
The `Cache` tasks sees the entry and downloads it, but the `FlutterInstall` task just starts to download it again.

**Comment by hey24sheep** [comment]
I see, I thought on the latest packages it might be fixed. But the issue I linked here is still open on Azure.

**Comment by MarkerwApk** [comment]
Hi, Manually cache, working for me. But Cache execution time == Download and unzip time from Internet :)

FLUTTER_CACHE_FOLDER: $(Pipeline.Workspace)/.flutter

![image](https://user-images.githubusercontent.com/8994965/150108097-805cffe9-fdf7-42b0-a611-6d0b74101f3d.png)

**Comment by hey24sheep** [comment]
@MarkerwApk Does your cache key is same as the[ Flutter Install Task Key](https://github.com/hey24sheep/azure-flutter-tasks/blob/f6f3044433fd6989aba6c5e0e35222e7cc72180e/tasks/install/index.ts#L95). If not, Flutter Install will re-fetch from internet. There is some issue with Caching on Azure.

**Comment by MarkerwApk** [comment]
I thing, it work properly.
First run:
![image](https://user-images.githubusercontent.com/8994965/150474127-c33bec05-8d14-4db0-b52a-6bb490248213.png)
![image](https://user-images.githubusercontent.com/8994965/150474336-d348ff1e-6cbf-463d-be2b-2ffd0208f772.png)


Second run(1 task has changed order):
![image](https://user-images.githubusercontent.com/8994965/150474179-811cfb86-c383-4d49-bbd0-a10f8ffb8e9c.png)
![image](https://user-images.githubusercontent.com/8994965/150474269-4883b0ad-cbaf-4070-b3bf-2fc8a94e85cb.png)

**Comment by hey24sheep** [comment]
@MarkerwApk  Yes, it is working, otherwise all other tasks would have failed.

**Comment by hey24sheep** [comment]
This solution must be fixed now. There was a bug with how caching tool uses the semver. If you could read this [issue](https://github.com/hey24sheep/azure-flutter-tasks/issues/46). I have pushed the fixes for this. Caching should work now. 

If anyone tests it please let me know here.

**Comment by ChristianNavolskyi** [comment]
Seems like I was missing the `cacheHitVar` in the `Cache` task, silly me.

Caching and restoring is working, but the cache restoration time is painfully long. But I think that is not on you/this plugin.

Thanks for the help and thanks to @MarkerwApk for the example, there I found the missing line in my setup.

**Comment by hey24sheep** [comment]
I see, I am closing this issue now as the caching should be fixed on the latest version. If not, for some reason, feel free to create a new issue or re-open this one. I will be happy to help.

**Comment by brim-borium** [comment]
Hi @hey24sheep for caching to work do I just run Flutter Install in my different stages of the CI or do I have to go the way that @MarkerwApk mentions in this comment? 
https://github.com/hey24sheep/azure-flutter-tasks/issues/2#issuecomment-1016272551

**Comment by hey24sheep** [comment]
@brim-borium caching should work fine. I would recommend you to run it normally and check if it loads the data from cache (it should, unless Microsoft still has the issue). 

If it doesn't use cache then you can download my other cache extension and follow the above mentioned steps.

**Comment by sarinupreti2021** [comment]
> Hi, Manually cache, working for me. But Cache execution time == Download and unzip time from Internet :)
> 
> FLUTTER_CACHE_FOLDER: $(Pipeline.Workspace)/.flutter
> 
> ![image](https://user-images.githubusercontent.com/8994965/150108097-805cffe9-fdf7-42b0-a611-6d0b74101f3d.png)

Can you share your yaml file. I am stuck in the same situation for adding caching

**Comment by WieFel** [comment]
I got it to work for my CI pipeline with the following setup:
```yaml
- task: Cache@2
  displayName: 'Flutter Cache'
  inputs:
    key: 'flutter|"$(FlutterVersion)"|"$(Agent.OS)"'
    path: '$(Agent.ToolsDirectory)/Flutter/$(FlutterVersion)/linux/flutter'
    cacheHitVar: 'FLUTTER_CACHE_RESTORED'

- task: FlutterEnv@0
  displayName: 'Flutter Env'
  inputs:
    customPath: '$(Agent.ToolsDirectory)/Flutter/$(FlutterVersion)/linux/flutter'
  condition: eq(variables.FLUTTER_CACHE_RESTORED, 'true')

- task: FlutterInstall@0
  displayName: 'Flutter install'
  inputs:
    channel: 'stable'
    version: 'custom'
    customVersion: '$(FlutterVersion)'
  condition: ne(variables.FLUTTER_CACHE_RESTORED, 'true')
```

I defined `FlutterVersion` in the pipeline's "Variables"
<img width="464" alt="Image" src="https://github.com/user-attachments/assets/a7a7db73-0740-4b85-ba1f-dad2a7210c0a" />

Be aware that, if you use a build agent other than ubuntu, the Flutter installation path `path: '$(Agent.ToolsDirectory)/Flutter/$(FlutterVersion)/linux/flutter'` might be different for you. You can figure it out by adding a `flutter doctor -v` to your pipeline.

**Comment by ndnam198** [comment]
the solution that works for me in 5/2025. This takes into account the agent host OS so we determine installed path based on it rather than hardcoded path.

```yml
parameters:
  flutterVersion:
    type: string
    default: '3.27.3'
  channel:
    type: string
    default: 'stable'

steps:
  - script: |
      if [ "$(Agent.OS)" == "Darwin" ]; then
        folder="$(Agent.ToolsDirectory)/Flutter/${{ parameters.flutterVersion }}/macos/flutter"
      else
        folder="$(Agent.ToolsDirectory)/Flutter/${{ parameters.flutterVersion }}/linux/flutter"
      fi
      echo "##vso[task.setvariable variable=FLUTTER_CACHE_PATH]$folder"
    displayName: 'Determine Flutter cache path'

  - task: Cache@2
    displayName: 'Cache Flutter SDK'
    continueOnError: true
    inputs:
      key: 'flutter|"$(Agent.OS)"|"${{ parameters.flutterVersion }}"'
      restoreKeys: 'flutter'
      path: '$(FLUTTER_CACHE_PATH)'
      cacheHitVar: 'FLUTTER_CACHE_RESTORED'

  - task: Hey24sheep.flutter.flutter-env.FlutterEnv@0
    displayName: 'Setup Flutter (cached)'
    condition: eq(variables.FLUTTER_CACHE_RESTORED, 'true')
    inputs:
      customPath: '$(FLUTTER_CACHE_PATH)'
      pathType: 'customPath'

  - task: Hey24sheep.flutter.flutter-install.FlutterInstall@0
    displayName: 'Install Flutter (cache miss)'
    condition: ne(variables.FLUTTER_CACHE_RESTORED, 'true')
    inputs:
      channel: ${{ parameters.channel }}
      version: 'custom'
      customVersion: ${{ parameters.flutterVersion }}
```
